### ISSUE TITLE
[modern-icons] Duplicated icons

### ISSUE THREAD

**Issue by Neoskimmer** [schooltape/schooltape#103]
### What happened?

![Drawing-2](https://github.com/user-attachments/assets/ccb1f203-3b20-4c92-aa4a-beecb20b0421)
![Drawing](https://github.com/user-attachments/assets/487510f0-aa37-435f-ad79-8a7dcd764f2b)

Double icons when modern icons is on. (Also, Modern Icons works on my end now!!!!!)

### Version

The newest one I guess????

### What browsers are you seeing the problem on?

Firefox

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by Neoskimmer** [comment]
(I went and blacked my own name out, that's not a bug :/

**Comment by 42Willow** [comment]
Have you tried refreshing your page? How come the modern icons have been injected in the first image when the plugin is disabled in the first image. Also, can you please let me know what version you are on (it is under settings)

**Comment by Neoskimmer** [comment]
Ah thanks for the censor tip.

Yes, I did refresh the page, I can send a video if that's more helpful. I have no idea why the modern icons have been injected after it's turned off.
![Screen Shot 2024-09-08 at 14 59 19](https://github.com/user-attachments/assets/48b57803-462b-4f54-9a40-eb871818c450)

My theory is that it's a caching bug, and Firefox has cached schoolbox with the images so when it loads the images a second time they appear a second time

(Have no idea tho)

**Comment by Neoskimmer** [comment]
My theory also works with another bug, which is when school tape is set to off, dark mode and modern icons still work

**Comment by 42Willow** [comment]
Is there anyway you can reproduce this on other machines/in a clean browsing profile reliably? I don't have this issue

**Comment by Neoskimmer** [comment]
Yeah, I can try, I just need to get chrome working on my laptop lol

**Comment by 42Willow** [comment]
Just confirming that this occurs after disabling the modern icons plugin *and* refreshing?

**Comment by 42Willow** [comment]
You can also try hard reloading the page with <kbd>shift</kbd> + <kbd>reload button</kbd>

**Comment by Neoskimmer** [comment]
Yes, and refreshing the page
Also, chrome refuses to work so you might have to wait a bit or something :/

**Comment by Neoskimmer** [comment]
Im gonna join the discord to make it easier to communicate btw

**Comment by 42Willow** [comment]
Solution uninstall/disable one of the two copies of Schooltape :eyes:
