### ISSUE TITLE
Misc styling issues

### ISSUE THREAD

**Issue by 42willow** [schooltape/schooltape#124]
![image](https://github.com/user-attachments/assets/f33defb4-ed83-41a3-806e-da00de1c012f)

- [x] Settings button (top right) disappears when no new notifications

![image](https://github.com/user-attachments/assets/c50fa2df-45bc-43b8-b29a-4c2932b1d67c)

- [ ] #158

![image](https://github.com/user-attachments/assets/bf1b3597-5c20-4840-8c8e-1776a547a875)
![image](https://github.com/user-attachments/assets/f294b059-fc97-4751-992c-e0dac81199f7)

- [x] Red background colour on active elements

![image](https://github.com/user-attachments/assets/1c450217-0e3f-4229-96a1-6d1cb9fd6402)

- [x] News article title text colour
- [x] Text sometimes has custom bg colour

![image](https://github.com/user-attachments/assets/27693573-14d1-45a9-9d1c-773494cea79e)

- [x] Colours on checkboxes

- [x] Misc issues in input boxes (eg on submissions)

- [x] Highlighted marks are not shown on submission results

**Comment by DragonIsGone** [comment]
settings button can just be removed from the CSS on 218:24 in catppuccin.css
