### ISSUE TITLE
WXT publishing for all major web stores

### ISSUE THREAD

**Issue by Neoskimmer** [schooltape/schooltape#64]
Publishing for `v3.0.0` onwards

- [x] Setup [Release Please](https://wxt.dev/get-started/publishing.html) | [example](https://github.com/catppuccin/github-file-explorer-icons)
- [x] Chrome Web Store
- [x] Firefox Addon Store
<del>- [ ] Edge Addons</del>

https://wxt.dev/get-started/publishing.html

----------

### Is your feature request related to a problem?

Hey there!
This isn't really an issue, just me being picky.
I'm a full-time Firefox user. I only use chrome at school because our school forces us too, which is really annoying because I can't install browser addons. So that sucks, but what I'm really here to be annoyed about is the firefox issue.

### Describe the solution you'd like

I really just want someone to help me make this a firefox addon. That's all I want. I can help, even though my knowledge of how to do this stuff is little.

### Describe alternatives you've considered

Using dark reader, but I tried that and the colours weren't right :((((
This is so much better :sob:

### Would you like to contribute code to this feature?

- [X] I'm interested in contributing code to this feature

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 42Willow** [comment]
Hello, I'm also a Firefox user :o
The extension is already signed for Firefox, just use the `.xpi` on the [releases page](https://github.com/42Willow/schooltape/releases/latest).

I'm planning on listing Schooltape on the mozilla addons store soon™ along with auto updating so I'll keep this issue open to track that.

**Comment by Neoskimmer** [comment]
Oh my gosh thank you so much :0

**Comment by Neoskimmer** [comment]
Ok I broke something
It used to do this which was fine and I just ignored it
![Screen Shot 2024-06-03 at 6 50 54 pm](https://github.com/42Willow/schooltape/assets/152151849/38deab79-5cf1-476f-bc3e-7d4b49850294)
But now it's doing this??????????????????
![Screen Shot 2024-06-03 at 6 51 49 pm](https://github.com/42Willow/schooltape/assets/152151849/07a1607e-ab47-41ce-a7a7-cb21af9665fc)

sorry for disturbing you :sob:

**Comment by 42Willow** [comment]
nono it's fine. It's weird it's doing that - maybe google icons is blocked or something.

Try disabling the `modern-icons` plugin
![image](https://github.com/42Willow/schooltape/assets/70784752/f64e5cb0-3ad3-4972-a659-880fd7f6eb02)

**Comment by Neoskimmer** [comment]
I think it's an issue with my wifi or something (or computer, since I use seperate computers for school and home). It only happens on my home computer. Google Icons isn't blocked at home OR at school, so 🤷

**Comment by 42Willow** [comment]
@Neoskimmer Can you access https://fonts.gstatic.com/s/materialiconsround/v100/LDItaoyNOAY6Uewc665JcIzCKsKc_M9flwmP.woff2?

**Comment by Neoskimmer** [comment]
Just tested.
https://fonts.gstatic.com/s/materialiconsround/v100/LDItaoyNOAY6Uewc665JcIzCKsKc_M9flwmP.woff2 downloads the woff 2 file, and https://fonts.googleapis.com/icon?family=Material+Icons works fine aswell. 
I use firefox at home so ye
got a bunch of errors
![Screen Shot 2024-06-04 at 5 40 54 pm](https://github.com/42Willow/schooltape/assets/152151849/91bdf8c4-58fc-4762-a4f9-e42b0443cea0)
![Screen Shot 2024-06-04 at 5 41 32 pm](https://github.com/42Willow/schooltape/assets/152151849/6c781e9a-7380-4452-91ae-70552e2a0e3f)
There are some warnings, but they aren't relevant :))))

**Comment by 42Willow** [comment]
@Neoskimmer Schooltape is now published on Firefox Add-ons

Please see here: https://github.com/schooltape/schooltape/releases/tag/v3.0.0
